'use strict';
const $=s=>document.querySelector(s);
const state={sequence:[],logs:[],sessions:[],sessionId:crypto.randomUUID?.()||String(Date.now())};
const KEY='tx_v10_ultimate_state';
const MODEL_NAMES=['Đa khung','Theo bệt','Đảo sau bệt','Cầu 1–1','Markov bậc 1','Markov bậc 2','Bayesian','Cửa sổ thích nghi','Runs test','Entropy','Tự tương quan','Change-point'];
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&Array.isArray(x.sequence)){Object.assign(state,x);}}catch(e){console.warn(e)}}
function parseSeq(raw){return [...raw.toUpperCase()].filter(c=>c==='T'||c==='X');}
function pct(n,d){return d?100*n/d:0}
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
function opposite(v){return v==='T'?'X':'T'}
function label(v){return v==='T'?'TÀI':v==='X'?'XỈU':'TRUNG LẬP'}
function signalClass(v){return v==='T'?'tai':v==='X'?'xiu':'neutral'}
function recent(arr,n){return arr.slice(Math.max(0,arr.length-n))}
function counts(arr){let t=0;for(const v of arr)if(v==='T')t++;return{t,x:arr.length-t}}
function currentRun(arr){if(!arr.length)return{side:null,len:0};const side=arr.at(-1);let len=0;for(let i=arr.length-1;i>=0&&arr[i]===side;i--)len++;return{side,len}}
function runs(arr){const out=[];if(!arr.length)return out;let s=arr[0],l=1;for(let i=1;i<arr.length;i++){if(arr[i]===s)l++;else{out.push({side:s,len:l});s=arr[i];l=1}}out.push({side:s,len:l});return out}
function longest(arr,side){return Math.max(0,...runs(arr).filter(r=>r.side===side).map(r=>r.len))}
function alternating(arr,n=6){if(arr.length<n)return false;const a=arr.slice(-n);return a.every((v,i)=>i===0||v!==a[i-1])}
function blocks22(arr){if(arr.length<8)return false;const a=arr.slice(-8);return a.every((v,i)=>i<2||v===a[Math.floor(i/2)*2])&&a[0]!==a[2]&&a[2]!==a[4]&&a[4]!==a[6]}
function windowSignal(arr){const ws=[10,20,50,100].filter(n=>arr.length>=Math.min(n,8));let score=0,used=0;for(const n of ws){const a=recent(arr,n),c=counts(a),d=(c.t-c.x)/a.length;score+=d*(1+Math.log10(n));used++}if(!used)return modelNeutral('Cần ≥8 ván');const p=clamp(50+Math.abs(score/used)*55,50,90);return mk(Math.abs(score)<.04?null:score>0?'T':'X',p,arr.length,'Đa khung');}
function followRun(arr){const r=currentRun(arr);if(r.len<2)return modelNeutral('Chưa có bệt ≥2');return mk(r.side,50+Math.min(25,r.len*3),r.len,'Theo bệt');}
function reverseRun(arr){const r=currentRun(arr);if(r.len<2)return modelNeutral('Chưa có bệt ≥2');return mk(opposite(r.side),52+Math.min(24,r.len*3),r.len,'Đảo bệt');}
function oneOne(arr){if(arr.length<4||!alternating(arr,4))return modelNeutral('Không phải cầu 1–1');return mk(opposite(arr.at(-1)),58,4,'Cầu 1–1');}
function markov(arr,order){if(arr.length<order+8)return modelNeutral(`Cần ≥${order+8} ván`);const key=arr.slice(-order).join('');let t=1,x=1,samples=0;for(let i=order;i<arr.length;i++){if(arr.slice(i-order,i).join('')===key){arr[i]==='T'?t++:x++;samples++}}const p=t/(t+x);if(samples<3)return modelNeutral('Mẫu chuyển trạng thái quá ít');return mk(p>.5?'T':p<.5?'X':null,50+Math.abs(p-.5)*90,samples,`Markov ${order}`);}
function bayesian(arr){if(arr.length<8)return modelNeutral('Cần ≥8 ván');const c=counts(arr),a=1+c.t,b=1+c.x,p=a/(a+b);return mk(Math.abs(p-.5)<.025?null:p>.5?'T':'X',50+Math.abs(p-.5)*80,arr.length,'Bayesian');}
function adaptive(arr){if(arr.length<12)return modelNeutral('Cần ≥12 ván');const candidates=[8,12,20,30,50].filter(n=>n<=arr.length);let best=null;for(const n of candidates){const a=recent(arr,n),c=counts(a),edge=Math.abs(c.t-c.x)/n;const score=edge/Math.sqrt(n);if(!best||score>best.score)best={n,score,side:c.t>=c.x?'T':'X',edge}}return mk(best.edge<.08?null:best.side,50+best.edge*65,best.n,`Cửa sổ ${best.n}`);}
function runsTestModel(arr){if(arr.length<20)return modelNeutral('Cần ≥20 ván');const c=counts(arr),R=runs(arr).length;const mean=1+2*c.t*c.x/arr.length;const variance=(2*c.t*c.x*(2*c.t*c.x-arr.length))/(arr.length**2*(arr.length-1)||1);const z=variance>0?(R-mean)/Math.sqrt(variance):0;const r=currentRun(arr);if(Math.abs(z)<1)return modelNeutral(`Chuỗi gần ngẫu nhiên, z=${z.toFixed(2)}`);const side=z<0?r.side:opposite(arr.at(-1));return mk(side,50+Math.min(25,Math.abs(z)*8),arr.length,`Runs z=${z.toFixed(2)}`);}
function entropyModel(arr){if(arr.length<20)return modelNeutral('Cần ≥20 ván');const c=counts(arr),p=c.t/arr.length;const H=-(p? p*Math.log2(p):0)-((1-p)?(1-p)*Math.log2(1-p):0);if(H>.985)return modelNeutral(`Entropy cao ${H.toFixed(3)}`);return mk(p>.5?'T':'X',50+(1-H)*150,arr.length,`Entropy ${H.toFixed(3)}`);}
function autocorr(arr){if(arr.length<24)return modelNeutral('Cần ≥24 ván');const vals=arr.map(v=>v==='T'?1:-1),mean=vals.reduce((a,b)=>a+b,0)/vals.length;let best={lag:1,corr:0};for(let lag=1;lag<=Math.min(8,Math.floor(vals.length/3));lag++){let num=0,den=0;for(let i=0;i<vals.length-lag;i++){num+=(vals[i]-mean)*(vals[i+lag]-mean);den+=(vals[i]-mean)**2}const c=den?num/den:0;if(Math.abs(c)>Math.abs(best.corr))best={lag,corr:c}}if(Math.abs(best.corr)<.12)return modelNeutral(`Không có tự tương quan rõ`);const past=arr[arr.length-best.lag],side=best.corr>0?past:opposite(past);return mk(side,50+Math.min(25,Math.abs(best.corr)*60),arr.length,`Lag ${best.lag}, r=${best.corr.toFixed(2)}`);}
function changePoint(arr){if(arr.length<30)return modelNeutral('Cần ≥30 ván');const a=recent(arr,15),b=arr.slice(-30,-15),pa=counts(a).t/a.length,pb=counts(b).t/b.length,d=pa-pb;if(Math.abs(d)<.2)return modelNeutral(`Không có đổi pha rõ`);return mk(d>0?'T':'X',50+Math.min(30,Math.abs(d)*80),30,`Δ=${(d*100).toFixed(0)}%`);}
function mk(side,confidence,samples,note){return{side,confidence:clamp(confidence,50,95),samples,note}}
function modelNeutral(note){return{side:null,confidence:50,samples:0,note}}
function evaluateModels(arr){return[
  windowSignal(arr),followRun(arr),reverseRun(arr),oneOne(arr),markov(arr,1),markov(arr,2),bayesian(arr),adaptive(arr),runsTestModel(arr),entropyModel(arr),autocorr(arr),changePoint(arr)
].map((m,i)=>({...m,name:MODEL_NAMES[i]}));}
function predictAt(arr,idx,modelIndex){const prefix=arr.slice(0,idx);return evaluateModels(prefix)[modelIndex].side}
function backtest(arr){return MODEL_NAMES.map((name,mi)=>{let ok=0,n=0;for(let i=8;i<arr.length;i++){const p=predictAt(arr,i,mi);if(p){n++;if(p===arr[i])ok++}}const rate=pct(ok,n);const sampleTrust=clamp(n/80,0,1);const edge=Math.max(0,(rate-50)/25);const weight=clamp((.35+.65*sampleTrust)*(.5+.5*edge),.15,1);return{name,ok,n,rate,sampleTrust,weight}})}
function aggregate(models,bts){let t=0,x=0,active=0;models.forEach((m,i)=>{if(!m.side)return;active++;const bt=bts[i],sampleFactor=clamp(bt.n/50,.25,1);const perfFactor=clamp(.5+(bt.rate-50)/30,.25,1.25);const w=(m.confidence/100)*sampleFactor*perfFactor;if(m.side==='T')t+=w;else x+=w});const total=t+x;const side=total===0?null:Math.abs(t-x)/total<.08?null:t>x?'T':'X';const agreement=total?100*Math.max(t,x)/total:0;return{side,agreement,t,x,active}}
function render(){const arr=state.sequence,models=evaluateModels(arr),bts=backtest(arr),agg=aggregate(models,bts);$('#statusTotal').textContent=`${arr.length} ván`;$('#statusTime').textContent=`Cập nhật: ${new Date().toLocaleTimeString('vi-VN')}`;renderChips(arr);renderVerdict(agg,models);renderModels(models,bts);renderWindows(arr);renderPatterns(arr);renderCharts(arr);renderBacktest(bts);renderLogs();renderSessions();save()}
function renderChips(arr){const box=$('#chips');if(!arr.length){box.className='chips empty';box.textContent='Chưa có dữ liệu.';return}box.className='chips';box.innerHTML=arr.map((v,i)=>`<span class="chip ${v==='T'?'t':'x'}" title="Ván ${i+1}">${v}</span>`).join('')}
function renderVerdict(a,models){$('#modelCount').textContent=`${a.active} mô hình đủ dữ liệu`;const tv=models.filter(m=>m.side==='T').length,xv=models.filter(m=>m.side==='X').length,nv=models.length-tv-xv;$('#taiVotes').textContent=tv;$('#xiuVotes').textContent=xv;$('#neutralVotes').textContent=nv;const el=$('#verdictText');el.className=`verdict ${signalClass(a.side)}`;el.textContent=a.side?`NGHIÊNG ${label(a.side)}`:'CHƯA CÓ LỢI THẾ RÕ';$('#confidenceText').textContent=`Độ đồng thuận trọng số: ${a.agreement.toFixed(1)}%`;$('#verdictReason').textContent=a.active<3?'Cần thêm dữ liệu để nhiều mô hình cùng hoạt động.':a.side?`${tv} mô hình nghiêng Tài, ${xv} mô hình nghiêng Xỉu; trọng số được điều chỉnh theo backtest.`:'Các mô hình đang mâu thuẫn hoặc chênh lệch chưa đủ lớn.'}
function renderModels(models,bts){$('#modelCards').innerHTML=models.map((m,i)=>`<article class="modelCard"><div class="head"><b>${i+1}. ${m.name}</b><span>${bts[i].n?`${bts[i].rate.toFixed(1)}% OOS`:'Chưa BT'}</span></div><div class="signal ${signalClass(m.side)}">${label(m.side)}</div><div class="meter"><i style="width:${m.confidence}%"></i></div><div class="modelMeta"><span>${m.note}</span><span>${m.confidence.toFixed(1)}%</span></div></article>`).join('')}
function renderWindows(arr){const ws=[10,20,50,100,500,arr.length];const labels=['10 ván gần nhất','20 ván gần nhất','50 ván gần nhất','100 ván gần nhất','500 ván gần nhất','Toàn bộ'];$('#windowTable tbody').innerHTML=ws.map((n,i)=>{const a=i===5?arr:recent(arr,n),c=counts(a),diff=a.length?100*(c.t-c.x)/a.length:0;return`<tr><td>${labels[i]}</td><td>${a.length}</td><td>${c.t}</td><td>${c.x}</td><td>${pct(c.t,a.length).toFixed(1)}%</td><td>${diff>=0?'+':''}${diff.toFixed(1)}%</td></tr>`}).join('')}
function shannon(arr){if(!arr.length)return 0;const c=counts(arr),p=c.t/arr.length,q=c.x/arr.length;return -(p?p*Math.log2(p):0)-(q?q*Math.log2(q):0)}
function renderPatterns(arr){const r=currentRun(arr),rs=runs(arr),c=counts(arr);const items=[['Ván gần nhất',arr.length?label(arr.at(-1)):'—'],['Chuỗi hiện tại',r.side?`${label(r.side)} ${r.len}`:'—'],['Chuỗi dài nhất Tài',longest(arr,'T')],['Chuỗi dài nhất Xỉu',longest(arr,'X')],['Cầu 1–1',alternating(arr,6)?'Đang hình thành':'Không rõ'],['Cầu 2–2',blocks22(arr)?'Đang hình thành':'Không rõ'],['Số chuỗi',rs.length],['Entropy',arr.length?shannon(arr).toFixed(3):'—'],['Tỷ lệ Tài',arr.length?`${pct(c.t,arr.length).toFixed(1)}%`:'—'],['Tỷ lệ Xỉu',arr.length?`${pct(c.x,arr.length).toFixed(1)}%`:'—']];$('#patternGrid').innerHTML=items.map(([a,b])=>`<div class="patternItem"><small>${a}</small><strong>${b}</strong></div>`).join('')}
function drawAxes(ctx,w,h){ctx.clearRect(0,0,w,h);ctx.strokeStyle='#294566';ctx.lineWidth=1;for(let y=30;y<h-20;y+=(h-50)/4){ctx.beginPath();ctx.moveTo(38,y);ctx.lineTo(w-10,y);ctx.stroke()}ctx.strokeStyle='#6681a7';ctx.beginPath();ctx.moveTo(38,15);ctx.lineTo(38,h-25);ctx.lineTo(w-10,h-25);ctx.stroke()}
function renderCharts(arr){const c=$('#trendCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height;drawAxes(ctx,w,h);if(arr.length){const vals=[];for(let i=0;i<arr.length;i++){const a=arr.slice(Math.max(0,i-19),i+1),cc=counts(a);vals.push(100*cc.t/a.length)}ctx.strokeStyle='#33c7ff';ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>{const x=40+i*(w-55)/Math.max(1,vals.length-1),y=(h-25)-v*(h-50)/100;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#dcecff';ctx.font='16px sans-serif';ctx.fillText(`Hiện tại: ${vals.at(-1).toFixed(1)}% Tài`,45,28)}const rc=$('#runCanvas'),rctx=rc.getContext('2d');drawAxes(rctx,rc.width,rc.height);const dist={T:{},X:{}};for(const r of runs(arr))dist[r.side][Math.min(r.len,6)]=(dist[r.side][Math.min(r.len,6)]||0)+1;const max=Math.max(1,...Object.values(dist.T),...Object.values(dist.X));for(let i=1;i<=6;i++){const x=60+(i-1)*110,tw=(dist.T[i]||0),xw=(dist.X[i]||0);rctx.fillStyle='#36d278';rctx.fillRect(x,(h-30)-tw/max*180,32,tw/max*180);rctx.fillStyle='#ff5964';rctx.fillRect(x+38,(h-30)-xw/max*180,32,xw/max*180);rctx.fillStyle='#dcecff';rctx.fillText(i===6?'6+':String(i),x+22,h-8)}renderHeatmap(dist)}
function renderHeatmap(dist){let html='<div class="heatCell heatHead">Bên</div>'+[1,2,3,4,5,'6+'].map(x=>`<div class="heatCell heatHead">${x}</div>`).join('');for(const side of ['T','X']){html+=`<div class="heatCell heatHead">${label(side)}</div>`;for(let i=1;i<=6;i++){const v=dist[side][i]||0;html+=`<div class="heatCell" style="background:${side==='T'?`rgba(54,210,120,${.12+Math.min(.75,v/15)})`:`rgba(255,89,100,${.12+Math.min(.75,v/15)})`}">${v}</div>`}}$('#heatmap').innerHTML=html}
function renderBacktest(bts){$('#backtestTable tbody').innerHTML=bts.map(b=>`<tr><td>${b.name}</td><td>${b.ok}</td><td>${b.n}</td><td>${b.n?b.rate.toFixed(1)+'%':'—'}</td><td>${b.n<20?'Thấp':b.n<60?'Trung bình':'Cao'}</td><td>${(b.weight*100).toFixed(0)}%</td></tr>`).join('')}
function renderLogs(){const rows=[...state.logs].reverse().map(l=>`<tr><td>${new Date(l.time).toLocaleString('vi-VN')}</td><td>${label(l.side)}</td><td>${l.agreement.toFixed(1)}%</td><td>${l.result?label(l.result):'Chờ'}</td><td>${l.result?(l.result===l.side?'Đúng':'Sai'):'Đã khóa'}</td></tr>`).join('');$('#signalTable tbody').innerHTML=rows||'<tr><td colspan="5">Chưa có tín hiệu được khóa.</td></tr>'}
function addResult(v){for(const l of state.logs)if(!l.result)l.result=v;state.sequence.push(v);render()}
function lockSignal(){const m=evaluateModels(state.sequence),a=aggregate(m,backtest(state.sequence));if(!a.side)return alert('Chưa có tín hiệu rõ để khóa.');state.logs.push({time:Date.now(),side:a.side,agreement:a.agreement,result:null,sequenceLength:state.sequence.length});render()}
function download(name,text,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function csv(){const rows=[['STT','Kết quả'],...state.sequence.map((v,i)=>[i+1,label(v)])];return '\uFEFF'+rows.map(r=>r.join(',')).join('\n')}
function reportHtml(){const models=evaluateModels(state.sequence),a=aggregate(models,backtest(state.sequence));return`<!doctype html><meta charset="utf-8"><title>Báo cáo V10</title><style>body{font-family:Arial;max-width:900px;margin:auto;padding:30px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #aaa;padding:8px}</style><h1>Báo cáo Tài Xỉu V10 Ultimate</h1><p>Ngày xuất: ${new Date().toLocaleString('vi-VN')}</p><p>Tổng số ván: ${state.sequence.length}</p><h2>Kết luận mô tả: ${a.side?label(a.side):'Chưa có lợi thế rõ'}</h2><p>Độ đồng thuận: ${a.agreement.toFixed(1)}%</p><table><tr><th>Mô hình</th><th>Tín hiệu</th><th>Độ tin cậy</th><th>Ghi chú</th></tr>${models.map(m=>`<tr><td>${m.name}</td><td>${label(m.side)}</td><td>${m.confidence.toFixed(1)}%</td><td>${m.note}</td></tr>`).join('')}</table><p><b>Lưu ý:</b> Báo cáo chỉ mô tả dữ liệu lịch sử, không đảm bảo kết quả tương lai.</p>`}
function renderSessions(){const all=[...state.sessions,{id:state.sessionId,n:state.sequence.length,created:Date.now()}];$('#sessionSummary').textContent=`Phiên hiện tại: ${state.sessionId}\nSố phiên đã lưu: ${state.sessions.length}\nTổng dữ liệu phiên hiện tại: ${state.sequence.length} ván.`}
$('#addTai').onclick=()=>addResult('T');$('#addXiu').onclick=()=>addResult('X');$('#undoBtn').onclick=()=>{state.sequence.pop();render()};$('#clearBtn').onclick=()=>{if(confirm('Xóa toàn bộ dữ liệu hiện tại?')){state.sequence=[];render()}};$('#appendSequence').onclick=()=>{state.sequence.push(...parseSeq($('#sequenceInput').value));$('#sequenceInput').value='';render()};$('#replaceSequence').onclick=()=>{const a=parseSeq($('#sequenceInput').value);if(a.length){state.sequence=a;$('#sequenceInput').value='';render()}};$('#demoBtn').onclick=()=>{state.sequence=parseSeq('TXXTTXTXTXXTTTXXTXTTXXTXXTTXTTXXTXXT');render()};$('#imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;$('#previewImage').src=URL.createObjectURL(f);$('#imageReview').classList.remove('hidden')};$('#closeImage').onclick=()=>$('#imageReview').classList.add('hidden');$('#lockSignalBtn').onclick=lockSignal;$('#clearLogBtn').onclick=()=>{if(confirm('Xóa nhật ký tín hiệu?')){state.logs=[];render()}};$('#saveJson').onclick=()=>download(`tai-xiu-v10-backup-${Date.now()}.json`,JSON.stringify(state,null,2),'application/json');$('#restoreJson').onchange=async e=>{try{const x=JSON.parse(await e.target.files[0].text());if(!Array.isArray(x.sequence))throw Error();Object.assign(state,x);render()}catch{alert('File JSON không hợp lệ.')}};$('#exportCsv').onclick=()=>download(`tai-xiu-v10-${Date.now()}.csv`,csv(),'text/csv');$('#exportReport').onclick=()=>download(`bao-cao-v10-${Date.now()}.html`,reportHtml(),'text/html');$('#newSession').onclick=()=>{state.sessions.push({id:state.sessionId,n:state.sequence.length,created:Date.now(),sequence:[...state.sequence]});state.sessionId=crypto.randomUUID?.()||String(Date.now());state.sequence=[];render()};$('#compareSessions').onclick=()=>{const lines=state.sessions.map((s,i)=>`Phiên ${i+1}: ${s.n} ván`).join('\n');alert(lines||'Chưa có phiên cũ để so sánh.')};
load();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
